"""General interface definitions for distribution of Evolution Strategies."""

from __future__ import annotations

from abc import ABC, abstractmethod
from collections.abc import Generator

from maze.core.agent.policy import Policy
from maze.core.agent.torch_model import TorchModel
from maze.core.log_stats.log_stats import LogStats

import numpy as np


class ESRolloutResult:
    """Result structure for distributed rollouts."""

    def __init__(self, is_eval: bool):
        """:param is_eval: If True, the result was generated by evaluation rollouts, in which case the noise indices
        won't be set.
        """
        self.is_eval: bool = is_eval
        self.noise_indices: list[int] = []
        self.episode_stats: list[LogStats] = []


class ESDistributedRollouts(ABC):
    """Abstract base class of ES rollout distribution."""

    @abstractmethod
    def generate_rollouts(
        self,
        policy: Policy | TorchModel,
        max_steps: int | None,
        noise_stddev: float,
        normalization_stats: dict[str, tuple[np.ndarray, np.ndarray]],
    ) -> Generator[ESRolloutResult, None, None]:
        """Declare a new rollout task and start producing results that can be obtained from the returned generator.

        Note that different distribution strategies have different ways of balancing evaluation and training rollouts.

        :param policy: Multi-step policy encapsulating the policy networks
        :param max_steps: Optionally limit the rollout to a number of environment steps (horizon).
        :param noise_stddev: The standard deviation of the applied parameter noise.
        :param normalization_stats: Normalization statistics as calculated by the NormalizeObservationWrapper.
        """
