# @package wrappers

# limits the maximum number of time steps of an episode
maze.core.wrappers.time_limit_wrapper.TimeLimitWrapper:
  max_episode_steps: 200

# flattens the dictionary observations to work with DenseLayers
maze.core.wrappers.observation_preprocessing.preprocessing_wrapper.PreProcessingWrapper:
  pre_processor_mapping:
    - observation: inventory
      _target_: maze.preprocessors.FlattenPreProcessor
      keep_original: false
      config:
        num_flatten_dims: 2