# Environment for Maze core.
name: maze
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - cudatoolkit
  - pytorch
  - pygraphviz
  - scipy
  - pip
  - pandas
  - numpy
  # swig is needed for Box2D, box2d-py but does not work with the pip installer
  - swig
  - pip:
      - fsspec
      - jupyterlab
      - pyyaml
      - tensorboard>=2.19
      - requests
      - pillow
      - hydra-core
      - hydra-optuna-sweeper
      - gymnasium[all]
      - networkx
      - matplotlib
      - seaborn
      - tqdm
      - imageio
      - torch_geometric
      # train
      - redis
      - cloudpickle
      # testing
      - pytest
      - pytest-cov
      - pytest-xdist
      - pytest-random-order
      - pytest-timeout
      - pytest-redis