# @package model
_target_: maze.perception.models.custom_model_composer.CustomModelComposer

distribution_mapper_config: []

policy:
  _target_: maze.perception.models.policies.ProbabilisticPolicyComposer
  networks:
  - _target_: tutorial_maze_env.part06_struct_env.models.actor.SelectionPolicyNet
    non_lin: torch.nn.ReLU
    with_mask: false
  - _target_: tutorial_maze_env.part06_struct_env.models.actor.CuttingPolicyNet
    non_lin: torch.nn.ReLU
    with_mask: false

critic:
  _target_: maze.perception.models.critics.StepStateCriticComposer
  networks:
    - _target_: tutorial_maze_env.part06_struct_env.models.critic.SelectionValueNet
      non_lin: torch.nn.ReLU
    - _target_: tutorial_maze_env.part06_struct_env.models.critic.CuttingValueNet
      non_lin: torch.nn.ReLU