# @package model
_target_: maze.perception.models.template_model_composer.TemplateModelComposer

distribution_mapper_config: []

model_builder:
  _target_: maze.perception.builders.ConcatModelBuilder

  shared_embedding_keys: ~

  observation_modality_mapping:
    inventory-flatten: feature
    ordered_piece: feature
    selected_piece: feature

  modality_config:
    feature:
      block_type: maze.perception.blocks.DenseBlock
      block_params:
        hidden_units: [32]
        non_lin: torch.nn.ReLU
    hidden: {}
    recurrence: {}

policy:
  _target_: maze.perception.models.policies.ProbabilisticPolicyComposer

critic:
  _target_: maze.perception.models.critics.SharedStateCriticComposer