# @package model
_target_: maze.perception.models.custom_model_composer.CustomModelComposer

distribution_mapper_config:
    - action_space: gym.spaces.Box
      distribution: maze.distributions.squashed_gaussian.SquashedGaussianProbabilityDistribution

policy:
  _target_: maze.perception.models.policies.ProbabilisticPolicyComposer
  networks:
    - _target_: maze.perception.models.built_in.flatten_concat.FlattenConcatPolicyNet
      non_lin: torch.nn.Tanh
      hidden_units: [256, 256]

critic:
  _target_: maze.perception.models.critics.StateCriticComposer
  networks:
    - _target_: maze.perception.models.built_in.flatten_concat.FlattenConcatStateValueNet
      non_lin: torch.nn.Tanh
      hidden_units: [256, 256]