# @package model
_target_: maze.perception.models.custom_model_composer.CustomModelComposer

distribution_mapper_config: []

_:
  non_lin: torch.nn.Tanh

policy:
  _target_: maze.perception.models.policies.ProbabilisticPolicyComposer
  networks:
    - _target_: maze.perception.models.built_in.flatten_concat.FlattenConcatPolicyNet
      non_lin: ${model._.non_lin}
      hidden_units: [256, 256]

critic:
  _target_: maze.perception.models.critics.StateCriticComposer
  networks:
    - _target_: maze.perception.models.built_in.flatten_concat.FlattenConcatStateValueNet
      non_lin: ${model._.non_lin}
      hidden_units: [256, 256]