# @package model
_target_: maze.perception.models.custom_model_composer.CustomModelComposer

shared_embedding: true

distribution_mapper_config:
  - action_space: gym.spaces.Box
    distribution: maze.distributions.squashed_gaussian.SquashedGaussianProbabilityDistribution

policy:
  _target_: maze.perception.models.policies.ProbabilisticPolicyComposer
  networks:
    - _target_: maze.perception.models.built_in.flatten_concat_shared.FlattenConcatPolicyNet
      non_lin: torch.nn.Tanh
      hidden_units: [ 256 ]
      head_units: [ 256 ]
  substeps_with_separate_agent_nets: [ ]

critic:
  _target_: maze.perception.models.critics.SharedStateCriticComposer
  networks:
    - _target_: maze.perception.models.built_in.flatten_concat_shared.FlattenConcatStateValueNet
      non_lin: torch.nn.Tanh
      head_units: [ 256 ]