# @package model
_target_: maze.perception.models.template_model_composer.TemplateModelComposer

distribution_mapper_config:
  - action_space: gym.spaces.Box
    distribution: maze.distributions.squashed_gaussian.SquashedGaussianProbabilityDistribution

model_builder:
  _target_: maze.perception.builders.ConcatModelBuilder

  shared_embedding_keys: ~

  observation_modality_mapping:
    observation: feature

  modality_config:
    feature:
      block_type: maze.perception.blocks.DenseBlock
      block_params:
        hidden_units: [ 128 ]
        non_lin: torch.nn.Tanh
    hidden:
      block_type: maze.perception.blocks.DenseBlock
      block_params:
        hidden_units: [ 128 ]
        non_lin: torch.nn.Tanh
    recurrence: { }

policy:
  _target_: maze.perception.models.policies.ProbabilisticPolicyComposer

critic: ~