# @package policy
_target_: tutorial_maze_env.part06_struct_env.policies.greedy_policy.GreedyPolicy
action_conversion:
  _target_: maze_envs.logistics.cutting_2d.space_interfaces.action_conversion.dict.ActionConversion
  max_pieces_in_inventory: ${env.max_pieces_in_inventory}
