# @package runner

# Where to save the best model (output directory handled by hydra)
state_dict_dump_file: "state_dict.pt"

# If provided the state dict will be dumped every 'dump_interval' epochs.
dump_interval: ~

# Where to save the env spaces configuration (output directory handled by hydra)
spaces_config_dump_file: "spaces_config.pkl"

# Number of rollouts to collect normalization statistics from at the beginning of the training.
normalization_samples: 1000
