# @package _group_
_target_: maze.core.rollout.sequential_rollout_runner.SequentialRolloutRunner

# Total number of episodes to run
n_episodes: 50

# Max steps per episode to perform
max_episode_steps: 200

# If true, trajectory data will be recorded and stored in `trajectory_data` directory
record_trajectory: true

# If true, event logs will be recorded and stored in `event_logs_directory
record_event_logs: true

# If true, will render the environment state after each step of the rollout
render: false

# (Note that the default output directory is handled by Hydra)
