# @package runner
_target_: maze.core.rollout.sequential_rollout_runner.SequentialRolloutRunner

# Total number of episodes to run. If explicit seeds are given the actual number of episodes is given by
#  min(n_episodes, n_seeds).
n_episodes: 50

# Max steps per episode to perform
max_episode_steps: 0

# Deterministic or stochastic action sampling
deterministic: true

# If true, trajectory data will be recorded and stored in `trajectory_data` directory
record_trajectory: false

# If true, event logs will be recorded and stored in `event_logs_directory
record_event_logs: true

# If true, will render the environment state after each step of the rollout
render: false

# If provided, the config of the model and policy config from the input_dir will be used.
# Optionally the environment or/and the wrappers config can be used from the input_dir.
# Example for using the environment config from the input_dir:
#use_input_dir_config:
#  use_input_dir_env: True
#  use_input_dir_wrappers: False
use_input_dir_config: ~

# (Note that the default output directory is handled by Hydra)
