# @package model
_target_: maze.perception.models.default_model_composer.DefaultModelComposer

# specify distribution mapping
# (here we use a default distribution mapping)
distribution_mapper_config: []

# specifies the architecture of default models
model_builder:
  _target_: maze.perception.builders.ConcatModelBuilder

  # Specify up to which keys the embedding should be shared between actor and critic
  shared_embedding_keys: ~

  # specifies the modality type of each observation
  observation_modality_mapping:
    observation: feature

  # specifies with which block to process a modality
  modality_config:
    # modality processing
    feature:
      block_type: maze.perception.blocks.DenseBlock
      block_params:
        hidden_units: [32, 32]
        non_lin: torch.nn.ReLU
    # preserved keys for the model builder
    hidden: {}
    recurrence: {}

# select policy type
policy:
  _target_: maze.perception.models.policies.ProbabilisticPolicyComposer

# select critic type
critic:
  _target_: maze.perception.models.critics.StateCriticComposer