# @package runner
_target_: maze.train.trainers.imitation.bc_runners.BCLocalRunner

# Number of concurrent evaluation envs
eval_concurrency: 4

# Specify the Dataset class used to load the trajectory data for training
dataset:
  _target_: maze.train.trainers.imitation.in_memory_data_set.InMemoryImitationDataSet
  trajectory_data_dir: trajectory_data
