# @package runner
_target_: "maze.train.trainers.sac.sac_runners.SACDevRunner"

# Number of concurrent evaluation envs
eval_concurrency: 0

# Specify the dataset class used to load the trajectory data for training, otherwise the initial replay buffer is
# sampled with the provided initial_sampling_policy
initial_demonstration_trajectories:
  _target_: maze.core.trajectory_recording.datasets.in_memory_dataset.InMemoryDataset
  input_data: trajectory_data
  n_workers: 5
  deserialize_in_main_thread: false
  trajectory_processor:
    _target_: maze.core.trajectory_recording.datasets.trajectory_processor.IdentityWithNextObservationTrajectoryProcessor