# @package env
_target_: tutorial_maze_env.part06_struct_env.env.struct_env_masked.struct_env_factory

# parametrizes the core environment
max_pieces_in_inventory: 50
raw_piece_size: [4, 3]
static_demand:
  - [1, 2]
  - [1, 2]
  - [1, 1]
  - [2, 2]
  - [1, 2]
  - [1, 1]