# @package wrappers
maze.core.wrappers.observation_stack_wrapper.ObservationStackWrapper:
  stack_config:
    - observation: observation
      keep_original: false
      tag: ~
      delta: false
      stack_steps: 4
maze.core.wrappers.observation_normalization.observation_normalization_wrapper.ObservationNormalizationWrapper:
  default_strategy: maze.normalization_strategies.MeanZeroStdOneObservationNormalizationStrategy
  default_strategy_config:
    clip_range: [-3, 3]
    axis: [0, 1]
  default_statistics: ~
  statistics_dump: statistics.pkl
  sampling_policy:
    _target_: maze.core.agent.random_policy.RandomPolicy
  exclude: ~
  manual_config: ~
maze.core.wrappers.monitoring_wrapper.MazeEnvMonitoringWrapper:
  observation_logging: false
  action_logging: true
  reward_logging: false