# @package wrappers

# limits the maximum number of time steps of an episode
maze.core.wrappers.time_limit_wrapper.TimeLimitWrapper:
  max_episode_steps: 180

# flattens the dictionary observations to work with DenseLayers
maze.core.wrappers.observation_preprocessing.preprocessing_wrapper.PreProcessingWrapper:
  pre_processor_mapping:
    - observation: inventory
      _target_: maze.preprocessors.FlattenPreProcessor
      keep_original: true
      config:
        num_flatten_dims: 2

# normalize observations to range [0, 1]
maze.core.wrappers.observation_normalization.observation_normalization_wrapper.ObservationNormalizationWrapper:
  default_strategy: maze.normalization_strategies.RangeZeroOneObservationNormalizationStrategy
  sampling_policy:
    _target_: maze.core.agent.random_policy.RandomPolicy
  default_strategy_config:
    clip_range: [~, ~]
    axis: ~
  default_statistics:
    min: 0
    max: 3
  statistics_dump: statistics.pkl
  exclude:
    - inventory_mask
    - cutting_mask
    - inventory_size
  manual_config: ~

# monitoring wrapper
maze.core.wrappers.monitoring_wrapper.MazeEnvMonitoringWrapper:
  observation_logging: false
  action_logging: true
  reward_logging: false