# @package wrappers
maze.core.wrappers.observation_preprocessing.preprocessing_wrapper.PreProcessingWrapper:
    pre_processor_mapping:
        - observation: rgb_image
          _target_: my_project.preprocessors.custom.CustomPreProcessor
          keep_original: true
          config:
            num_flatten_dims: 2