# @package wrappers
maze.core.wrappers.observation_preprocessing.preprocessing_wrapper.PreProcessingWrapper:
    pre_processor_mapping:
        - observation: rgb_image
          _target_: maze.preprocessors.Rgb2GrayPreProcessor
          keep_original: true
          config:
            num_flatten_dims: 2
        - observation: categorical_feature
          _target_: maze.preprocessors.OneHotPreProcessor
          keep_original: false
          config: {}