name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  docker:

    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push base Docker image
        id: docker_build_base
        uses: docker/build-push-action@v2
        with:
          file: docker/maze-core.dockerfile
          push: true
          tags: enliteai/maze:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      -
        name: Build and push playground Docker image
        id: docker_build_playground
        uses: docker/build-push-action@v2
        with:
          file: docker/playground.dockerfile
          push: true
          tags: enliteai/maze:playground
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      -
        name: Build and push Docker image with RLlib and Tensorflow.
        id: docker_build_rllib_tensorflow
        uses: docker/build-push-action@v2
        with:
          file: docker/maze-core.dockerfile
          push: true
          build-args: opt_pip_installs=ray[rllib],tensorflow
          tags: enliteai/maze:rllib-tensorflow
      -
        # Temp fix for growing cache issue.
        # See https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md.
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
