# @package policy

# Example config file for loading trained models.

_target_: maze.core.agent.serialized_torch_policy.SerializedTorchPolicy

# (1) Specify where the state dict and spaces config to load reside
state_dict_file:  state_dict.pt
spaces_dict_file: spaces_config.pkl

# (2) If using observation normalization, you might want to check the wrappers config
#     to make sure the correct statistics are loaded.

model: ${model}

device: cpu

# If True actions are computed deterministically; else sample from the probability distribution
deterministic: false